### ISSUE TITLE
"Stop generation"/"Stop analysis" buttons don't work 

### ISSUE THREAD

**Issue by kgradzka** [10clouds/aiconsole#541] opened 2024-01-05 14:50 UTC
## Steps to Reproduce the Problem

1. Open new chat.
2. Prompt AIConsole with something that would require code generation/click "Guide me" button.
3. When agents starts replying try to click "Stop generation" or "Stop analysis" button.

## Specifications
- Platform: Win10

https://github.com/10clouds/aiconsole/assets/61430006/b4747770-c0a1-4228-b90a-ce0067ae3448

![stop_analysis_console](https://github.com/10clouds/aiconsole/assets/61430006/5fa90e3d-4faf-4993-bfbc-6b02b30f32e4)

https://github.com/10clouds/aiconsole/assets/61430006/dc3202d7-e02c-4cf4-9cd3-a23dd7a83648

**Comment by cielecki** [comment] 2024-01-08 12:15
Duplicate of #477

**Closed** 2024-01-08 12:16 UTC
Labels: bug, backend, critical
