### ISSUE TITLE
Infrastructure for versioning messages and materials [ACD-424]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#302] opened 2023-12-21 15:01 UTC
Migrated from issue: [ACD-424](https://10clouds.atlassian.net/browse/ACD-424) (Task)

potrzebny:,Powiązane z: ,  

[ACD-424]: https://10clouds.atlassian.net/browse/ACD-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment] 2024-01-03 22:41
Duplicate of #289

**Closed by cielecki** 2024-01-03 22:41 UTC
