### ISSUE TITLE
USER ACSESS / PERMISSION CONTROL

### ISSUE THREAD

**Issue by Globarti** [10clouds/aiconsole#703] opened 2024-01-29 11:02 UTC
During the meeting 29.01.24 we discussed a need for thinking threw the permissions levels for users of AIC.  
<img width="631" alt="image" src="https://github.com/10clouds/aiconsole/assets/1726746/59519d5a-8243-432d-ae1b-c8a90b7c9026">

The challange here is to brainstorm **all the potential use-cases** of the team work on AIC. Example:
- user can interact with material via chat BUT cant see the material itself
- user can not edit the project's materials but can override them for its own use
- ++

In the past it was mentioned also here:
https://github.com/10clouds/aiconsole/issues/556

@Globarti + @DVLevin -> THIS ISSUE requires analysis of the future way to interact with multi-user AIConsole concept!

**Comment by cielecki** [comment] 2024-02-02 06:25
Duplicate of #716

**Closed** 2024-02-02 06:40 UTC
Labels: concept needed
