### ISSUE TITLE
Changing the language in settings (spell checker) [ACD-837]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#386] opened 2023-12-28 21:01 UTC
Migrated from issue: [ACD-837](https://10clouds.atlassian.net/browse/ACD-837) (Task)

Conected to error ACD-812 

[ACD-837]: https://10clouds.atlassian.net/browse/ACD-837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment] 2024-01-03 21:40
Duplicate of #229

**Closed by cielecki** 2024-01-03 21:40 UTC
Labels: nice to have
