### ISSUE TITLE
Settings with excluded materials and agents along with an api for it [ACD-254]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#329] opened 2023-12-21 14:57 UTC
Migrated from issue: [ACD-254](https://10clouds.atlassian.net/browse/ACD-254) (Task)

The user should be able to interact with the settings using natural language.

[ACD-254]: https://10clouds.atlassian.net/browse/ACD-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment] 2024-01-03 22:51
No longer relevant

**Comment by cielecki** [comment] 2024-01-03 22:51
Duplicate of #206

**Closed by cielecki** 2024-01-03 22:51 UTC
