### ISSUE TITLE
Proper tutorial agent and materials about AIConsole [ACD-420]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#305] opened 2023-12-21 14:59 UTC
Migrated from issue: [ACD-420](https://10clouds.atlassian.net/browse/ACD-420) (Task)

Also make sure that there are no halucinations for questions on the welcome screen 

[ACD-420]: https://10clouds.atlassian.net/browse/ACD-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment] 2024-01-03 22:42
Duplicate of #304

**Closed by cielecki** 2024-01-03 22:42 UTC
