### ISSUE TITLE
Design review: After clicking edit I have a large area which looks wierd and blends with the background [ACD-820]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#226] opened 2023-12-21 15:22 UTC
Migrated from issue: [ACD-820](https://10clouds.atlassian.net/browse/ACD-820) (Bug)

[ACD-820]: https://10clouds.atlassian.net/browse/ACD-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by AGasior** [comment] 2024-01-11 12:21
Duplicated [#226](https://github.com/10clouds/aiconsole/issues/226)

**Comment by kgradzka** [comment] 2024-01-12 01:05
Duplicate of https://github.com/10clouds/aiconsole/issues/465.

**Closed by kgradzka** 2024-01-12 01:05 UTC
Labels: bug, frontend, qa
