### ISSUE TITLE
If the user wanted the manual to be available online, what then? And what if they have their own wiki and would like it to be the source of materials? [ACD-237]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#332] opened 2023-12-21 14:57 UTC
Migrated from issue: [ACD-237](https://10clouds.atlassian.net/browse/ACD-237) (Task)

[ACD-237]: https://10clouds.atlassian.net/browse/ACD-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment] 2024-01-02 10:38
Adapter for materials - an ability to pull them from any source (current toml files, but also notion, package.json etc, spreadsheets etc)

**Comment by cielecki** [comment] 2024-01-03 11:33
For Desktop:
- We don't need a storage layer for settings
- We need a configure storage layer for assets

**Comment by cielecki** [comment] 2024-02-02 04:52
Duplicate of #712

**Closed** 2024-02-02 04:52 UTC
Labels: backend, concept needed
