### ISSUE TITLE
How to organize directory sharing between multiple computers? [ACD-744]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#253] opened 2023-12-21 15:15 UTC
Migrated from issue: [ACD-744](https://10clouds.atlassian.net/browse/ACD-744) (Task)

[ACD-744]: https://10clouds.atlassian.net/browse/ACD-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment] 2024-01-03 22:35
Somewhat related to: #243 , maybe a duplicate?

**Comment by cielecki** [comment] 2024-01-03 22:35
Duplicate of #243

**Closed by cielecki** 2024-01-03 22:35 UTC
