### ISSUE TITLE
[Hosted] Registration

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#420] opened 2023-12-28 21:07 UTC
Migrated from issue: [ACD-418](https://10clouds.atlassian.net/browse/ACD-418) (Task)

[ACD-418]: https://10clouds.atlassian.net/browse/ACD-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment] 2024-01-03 20:52
Duplicate of #438

**Closed by cielecki** 2024-01-03 20:52 UTC
Labels: nice to have
