### ISSUE TITLE
Support for many open conversations at once [ACD-386]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#312] opened 2023-12-21 14:59 UTC
Migrated from issue: [ACD-386](https://10clouds.atlassian.net/browse/ACD-386) (Task)

[ACD-386]: https://10clouds.atlassian.net/browse/ACD-386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment] 2024-01-04 06:12
Duplicate of #306

**Closed by cielecki** 2024-01-04 06:12 UTC
Labels: frontend, backend
