### ISSUE TITLE
[Hosted] Log in

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#419] opened 2023-12-28 21:07 UTC
Migrated from issue: [ACD-419](https://10clouds.atlassian.net/browse/ACD-419) (Task)

[ACD-419]: https://10clouds.atlassian.net/browse/ACD-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment] 2024-01-03 21:03
Duplicate of #438

**Closed by cielecki** 2024-01-03 21:03 UTC
Labels: nice to have
