### ISSUE TITLE
[Research required] Make or use some framework for testing the quality of agents' work. [ACD-377]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#315] opened 2023-12-21 14:59 UTC
Migrated from issue: [ACD-377](https://10clouds.atlassian.net/browse/ACD-377) (Task)

The goal is for the framework to execute a command like "calculate five factorial" about 30 times and to verify the output, checking what percentage produced the expected result. Additionally, for inquiries such as "what are materials" - the AI Console's material should be used to respond to these questions, etc.

[ACD-377]: https://10clouds.atlassian.net/browse/ACD-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment] 2024-01-02 10:51
Duplicate of https://github.com/10clouds/aiconsole/issues/322

**Closed** 2024-01-02 10:52 UTC
Labels: backend
