### ISSUE TITLE
Image generation [ACD-865]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#384] opened 2023-12-28 20:45 UTC
Migrated from issue: [ACD-865](https://10clouds.atlassian.net/browse/ACD-865) (Task)

[ACD-865]: https://10clouds.atlassian.net/browse/ACD-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment] 2024-01-03 21:30
Duplicate of #291

**Closed by cielecki** 2024-01-03 21:30 UTC
Labels: nice to have
